name: unit

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 14

      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm run test:ci
